"use client";

import { FormEvent, useState } from "react";
import type { QuoteEstimate, QuoteEstimateInput, QuoteOption } from "@/modules/quotes/estimator";

type Receipt = { quote_number: string; state: string; requested_at: string };
type Tracking = { tracking_number: string; state: string; service_level: string; destination: { city?: string; country_code?: string }; events: Array<{ state: string; message: string; event_at: string }> };

async function jsonFetch<T>(url: string, init?: RequestInit): Promise<T> {
  const response = await fetch(url, init); const payload = await response.json();
  if (!response.ok) throw new Error(payload.error ?? "İşlem tamamlanamadı."); return payload as T;
}

const usd = new Intl.NumberFormat("tr-TR", { style: "currency", currency: "USD", maximumFractionDigits: 0 });

function shipmentFrom(form: FormData): QuoteEstimateInput {
  return { originCountry: String(form.get("originCountry")) as QuoteEstimateInput["originCountry"], originCity: String(form.get("originCity")), destinationCity: String(form.get("destinationCity")), destinationState: String(form.get("destinationState")), destinationPostalCode: String(form.get("destinationPostalCode")), pieces: Number(form.get("pieces")), lengthCm: Number(form.get("lengthCm")), widthCm: Number(form.get("widthCm")), heightCm: Number(form.get("heightCm")), totalWeightKg: Number(form.get("totalWeightKg")), cargoValueUsd: Number(form.get("cargoValueUsd")), mode: String(form.get("mode")) as QuoteEstimateInput["mode"], residential: form.get("residential") === "on", fragile: form.get("fragile") === "on", stackable: form.get("stackable") === "on" };
}

export default function QuotePortal() {
  const [estimate, setEstimate] = useState<QuoteEstimate | null>(null); const [shipment, setShipment] = useState<QuoteEstimateInput | null>(null);
  const [busy, setBusy] = useState(false); const [message, setMessage] = useState(""); const [receipt, setReceipt] = useState<Receipt | null>(null); const [tracking, setTracking] = useState<Tracking | null>(null);

  async function calculate(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); setBusy(true); setMessage(""); setReceipt(null); const nextShipment = shipmentFrom(new FormData(event.currentTarget));
    try { const result = await jsonFetch<{ data: QuoteEstimate }>("/api/v1/public/quotes/estimate", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(nextShipment) }); setShipment(nextShipment); setEstimate(result.data); requestAnimationFrame(() => document.getElementById("estimate-results")?.scrollIntoView({ behavior: "smooth", block: "start" })); }
    catch (error) { setMessage(error instanceof Error ? error.message : "Bu gönderi hesaplanamadı."); } finally { setBusy(false); }
  }

  async function requestQuote(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); if (!shipment) return; setBusy(true); setMessage(""); const form = new FormData(event.currentTarget);
    try { const result = await jsonFetch<{ data: Receipt }>("/api/v1/public/quotes/request", { method: "POST", headers: { "content-type": "application/json", "idempotency-key": crypto.randomUUID() }, body: JSON.stringify({ shipment, cargoDescription: form.get("cargoDescription"), website: form.get("website"), contact: { name: form.get("name"), email: form.get("email"), phone: form.get("phone"), company: form.get("company") } }) }); setReceipt(result.data); }
    catch (error) { setMessage(error instanceof Error ? error.message : "Kesin teklif isteği oluşturulamadı."); } finally { setBusy(false); }
  }

  async function track(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); setMessage(""); setTracking(null); const number = String(new FormData(event.currentTarget).get("trackingNumber") ?? "").trim();
    try { const result = await jsonFetch<{ data: Tracking }>(`/api/v1/tracking/${encodeURIComponent(number)}`); setTracking(result.data); } catch (error) { setMessage(error instanceof Error ? error.message : "Takip numarası bulunamadı."); }
  }

  const services = [["01","Tedarikçiden alım","Türkiye ve İtalya'daki üretici veya satıcıdan EXW teslim alma planı."],["02","Navlun ve gümrük","Deniz/hava seçenekleri, ABD liman karşılaştırması, broker ve evrak koordinasyonu."],["03","Konsolidasyon planı","Paket ölçülerine göre palet, LCL/FCL doluluk ve elle doğrulanan yerleşim planı."],["04","ABD içi teslimat","Paket için Easyship/Shopify, büyük ürün için uygun LTL veya beyaz eldiven ağı."],["05","Tek takip kaydı","Sağlayıcılar değişse bile müşteri için tek Gel Öz numarası ve anlaşılır kilometre taşları."],["06","İnsan desteği","Gecikme, hasar, gümrük ve teslimat sorularını sipariş kaydına bağlı yönetim."]];

  return <main className="publicSite">
    <header className="publicNav"><a className="publicBrand" href="#top"><span>GÖ</span><div><strong>Gel Öz</strong><small>Sınır ötesi lojistik</small></div></a><nav><a href="#services">Hizmetler</a><a href="#calculator">Fiyat hesapla</a><a href="#how-it-works">Nasıl çalışır?</a><a href="#track">Takip</a></nav><a className="operatorLink" href="/musteri">Müşteri girişi →</a></header>
    <section className="quoteHero" id="top"><div className="heroCopy"><p className="eyebrow">EXW · Türkiye ve İtalya → Amerika Birleşik Devletleri</p><h1>Evinizden çıkar.<br/>ABD&apos;de eve ulaşır.</h1><p>Mobilya, dekorasyon ve ev ürünlerinde tedarikçi kapısından ABD&apos;deki son adrese kadar tüm lojistik zincirini tek hizmet çatısı altında koordine ediyoruz. Tek muhatap, birleşik fiyat, tek Gel Öz takip numarası.</p><div className="heroActions"><a href="#calculator">Tahmini fiyatı gör</a><a href="#services">Hizmetleri incele</a></div><div className="heroProof"><span>Deniz LCL + FCL</span><span>Hava kargo</span><span>Gümrük koordinasyonu</span><span>Son kilometre</span></div></div><div className="routeVisual"><div className="routePoint"><small>ÇIKIŞ</small><strong>Türkiye / İtalya</strong><span>EXW alım + ihracat</span></div><div className="routeLine"><b>GÖ</b></div><div className="routePoint end"><small>VARIŞ</small><strong>Amerika Birleşik Devletleri</strong><span>İthalat + eve teslim</span></div></div></section>

    <section className="serviceStory" id="services"><div className="serviceStatement"><p className="eyebrow">Bugün</p><h2>Dağınık lojistik adımlarını tek bir hizmete dönüştürüyoruz.</h2><p>Gel Öz bugün kapasitesini olduğundan büyük göstermeden; seçilmiş nakliyeci, forwarder, gümrük müşaviri ve son kilometre sağlayıcılarını sizin adınıza koordine eder. Ürünü tedarikçiden alır, evrak ve navlun seçeneklerini toplar, rotayı karşılaştırır, teslimata kadar görünürlük sağlarız.</p></div><div className="serviceGrid">{services.map(([n,title,copy])=><article key={n}><span>{n}</span><h3>{title}</h3><p>{copy}</p></article>)}</div></section>
    <section className="futureSection"><div><p className="eyebrow">Yarın</p><h2>Daha fazla kapasiteyi Gel Öz ağına katıyoruz.</h2><p>Büyüdükçe kendi yönettiğimiz depolama ve konsolidasyon merkezleri; paketleme ve yeniden paketleme ekipleri; onaylı ambalaj sağlayıcıları; vardiya yönetimi; palet ve konteyner doluluk programlarıyla hizmet ağımızı genişleteceğiz.</p></div><div className="futureRail"><span>Depolama</span><span>Warehouse operasyonu</span><span>Paketleme sağlayıcıları</span><span>Palet konsolidasyonu</span><span>Konteyner programları</span><span>Vardiya ve kalite kontrol</span></div><small>Bu kabiliyetler kademeli devreye alınacaktır; bugünkü kesin teklif yalnızca doğrulanmış mevcut sağlayıcı ve kapasiteye dayanır.</small></section>
    <section className="homeFocus"><div><p className="eyebrow">Uzmanlık odağımız</p><h2>Evin karakterini taşıyan ürünler için daha dikkatli lojistik.</h2></div><div className="homeCards"><article><strong>Mobilya</strong><p>Koltuk, masa, sandalye, dolap ve büyük parçalar için ölçü, ağırlık, kırılganlık ve son kilometre gereksinimleri.</p></article><article><strong>Dekorasyon</strong><p>Aydınlatma, ayna, seramik, tekstil ve aksesuarlar için koruyucu paketleme ve konsolidasyon planı.</p></article><article><strong>Proje siparişleri</strong><p>Otel, perakende, iç mimari ve çok parçalı ev projelerinde sevkiyat gruplama ve teslimat koordinasyonu.</p></article></div></section>

    <section className="calculatorSection" id="calculator"><div className="sectionIntro"><p className="eyebrow">Standart planlama tahmini</p><h2>Kesin teklif istemeden önce rotaları karşılaştırın.</h2><p>Hesap makinesi hacim/ağırlık kurallarını, hava kargo hacimsel ağırlığını, beş ABD limanı için iç standartları, piyasa payını ve hacme göre Gel Öz koordinasyon ücretini uygular.</p></div>
      <form className="quoteCalculator" onSubmit={calculate}><div className="formBand"><span>01</span><div><strong>Rota</strong><small>Tedarikçi adresinden ABD&apos;deki son adrese</small></div></div><div className="quoteFields"><label>Çıkış ülkesi<select name="originCountry" defaultValue="TR"><option value="TR">Türkiye</option><option value="IT">İtalya</option></select></label><label>Çıkış şehri<input required name="originCity" defaultValue="İstanbul" /></label><label>Varış şehri<input required name="destinationCity" placeholder="New York" /></label><label>Eyalet<input required maxLength={40} name="destinationState" placeholder="NY" /></label><label>Posta kodu<input required name="destinationPostalCode" placeholder="10001" /></label><label>Taşıma modu<select name="mode" defaultValue="AUTO"><option value="AUTO">Benim için öner</option><option value="OCEAN_LCL">Deniz LCL</option><option value="OCEAN_FCL_20">20&apos; FCL</option><option value="AIR">Hava kargo</option></select></label></div><div className="formBand"><span>02</span><div><strong>Yük</strong><small>Ölçüler parça başına; ağırlık toplamdır</small></div></div><div className="quoteFields cargo"><label>Parça adedi<input required min="1" max="10000" name="pieces" type="number" defaultValue="1" /></label><label>Uzunluk cm<input required min="0.1" step="0.1" name="lengthCm" type="number" defaultValue="100" /></label><label>Genişlik cm<input required min="0.1" step="0.1" name="widthCm" type="number" defaultValue="80" /></label><label>Yükseklik cm<input required min="0.1" step="0.1" name="heightCm" type="number" defaultValue="60" /></label><label>Toplam ağırlık kg<input required min="0.1" step="0.1" name="totalWeightKg" type="number" defaultValue="120" /></label><label>Ürün değeri USD<input required min="1" step="0.01" name="cargoValueUsd" type="number" defaultValue="5000" /></label></div><div className="quoteChecks"><label><input name="stackable" type="checkbox" defaultChecked/> Üst üste konabilir</label><label><input name="fragile" type="checkbox"/> Kırılabilir</label><label><input name="residential" type="checkbox" defaultChecked/> Eve teslim</label><button disabled={busy}>{busy ? "Hesaplanıyor…" : "Rotaları karşılaştır"}</button></div></form>{message ? <div className="publicAlert">{message}</div> : null}
    </section>

    {estimate ? <section className="estimateResults" id="estimate-results"><div className="estimateSummary"><div><p className="eyebrow">{estimate.rateCardVersion}</p><h2>{estimate.cubicMeters} m³ · {estimate.oceanChargeableCbm} ücretlendirilebilir m³</h2><p>{estimate.airChargeableKg} hava kargo ücret ağırlığı · Önerilen {estimate.suggestedMode.replaceAll("_", " ")}</p></div><div className="estimateTag">PLANLAMA TAHMİNİ<br/><small>Sağlayıcı doğrulaması gerekir</small></div></div><div className="routeOptions">{estimate.options.map(option => <OptionCard key={option.optionCode} option={option}/>)}</div><div className="quoteFinePrint"><strong>Tahmine dahil olanlar</strong><p>Çıkış alımı, elleçleme, ana taşıma, varış elleçlemesi, gümrük müşaviri payı, evrak, sigorta payı, son kilometre, piyasa payı ve Gel Öz koordinasyonu.</p><strong>Henüz dahil olmayanlar</strong><p>{estimate.exclusions.join(" · ")}</p><small>{estimate.notice}</small></div><form className="firmQuoteForm" onSubmit={requestQuote}><div><p className="eyebrow">Tahminden operasyona</p><h2>Sağlayıcı destekli kesin teklif isteyin</h2><p>Teklif dosyanızı açar, gereken her etap için fiyat toplar, gümrük varsayımlarını doğrular ve süreli kesin teklif sunarız.</p></div><div className="contactGrid"><label>Ad soyad<input required name="name" /></label><label>İş e-postası<input required type="email" name="email" /></label><label>Şirket<input name="company" /></label><label>Telefon<input name="phone" /></label><label className="full">Ne gönderiyorsunuz?<textarea required minLength={2} maxLength={500} name="cargoDescription" placeholder="Mobilya, aydınlatma, dekorasyon…" /></label><label className="honey">Website<input tabIndex={-1} autoComplete="off" name="website" /></label><button disabled={busy}>{busy ? "Teklif açılıyor…" : "Kesin teklif iste"}</button></div></form>{receipt ? <div className="quoteReceipt"><span>Teklif dosyanız açıldı</span><strong>{receipt.quote_number}</strong><p>Gel Öz operasyon ekibi talebinizi artık teklif kuyruğunda görüyor. Takip için bu referansı saklayın.</p></div> : null}</section> : null}

    <section className="processSection" id="how-it-works"><div className="sectionIntro"><p className="eyebrow">Tek operasyon kaydı</p><h2>Tedarikçi kapısından müşteri kapısına.</h2></div><div className="processGrid">{[["01","Fiyatla","Forwarder, hava/deniz, gümrük müşaviri ve teslimat fiyatlarını topla."],["02","Doğrula","Ölçüleri, GTİP/HS kodlarını, ithalatçıyı, evrakı ve kapasiteyi onayla."],["03","Birleştir","Teslim al, kontrol et, gerektiğinde yeniden paketle, paletle ve LCL/FCL kararını ver."],["04","Teslim et","Onaylı sağlayıcıları rezerve et ve tek Gel Öz numarası altında olayları yayınla."]].map(([n,title,copy])=><article key={n}><span>{n}</span><h3>{title}</h3><p>{copy}</p></article>)}</div></section>
    <section className="publicTracking" id="track"><div><p className="eyebrow">Müşteri görünürlüğü</p><h2>Gel Öz siparişinizi takip edin.</h2><p>Operasyon ekibi sağlayıcı ve istisna geçmişini korurken, siz doğrulanmış ve anlaşılır teslimat kilometre taşlarını görürsünüz.</p><form onSubmit={track}><input required name="trackingNumber" placeholder="GOZ-26-…"/><button>Takip et</button></form><a className="trackingAccount" href="/musteri">Tüm gönderilerimi göster →</a></div>{tracking ? <div className="publicTimeline"><strong>{tracking.tracking_number}</strong><span>{tracking.state.replaceAll("_"," ")}</span>{tracking.events.map(event=><article key={`${event.state}-${event.event_at}`}><b>{event.state.replaceAll("_"," ")}</b><p>{event.message}</p><small>{new Date(event.event_at).toLocaleString("tr-TR")}</small></article>)}</div>:<div className="trackingBlank">Birleştirilmiş rotanız,<br/>adım adım görünür.</div>}</section>
    <section className="customerCta"><p className="eyebrow">Gel Öz hesabı</p><h2>Teklifleriniz, gönderileriniz, belgeleriniz ve destek talepleriniz tek yerde.</h2><a href="/musteri">Müşteri merkezini aç →</a></section>
    <footer><div className="publicBrand"><span>GÖ</span><div><strong>Gel Öz</strong><small>Sınır ötesi lojistik</small></div></div><p>Planlama tahminleri bağlayıcı değildir. Gümrük kararları ithalatçı ve lisanslı müşavire aittir; rezervasyonlar yetkili operasyon onayı gerektirir.</p><div><a href="/musteri">Müşteri girişi</a><a href="/operations">Personel girişi</a></div></footer>
  </main>;
}

function OptionCard({ option }: { option: QuoteOption }) {
  return <article className={option.recommended ? "routeOption recommended" : "routeOption"}>{option.recommended ? <span className="recommendFlag">ÖNERİLEN</span> : null}<p>{option.mode.replaceAll("_", " ")}</p><h3>{option.arrivalPort}</h3><strong>{usd.format(option.estimatedTotal)}</strong><small>{option.transitDaysMin}–{option.transitDaysMax} planlama günü</small><div><span>Sağlayıcı etapları <b>{usd.format(option.providerCost)}</b></span><span>Piyasa payı <b>{usd.format(option.marketContingency)}</b></span><span>Gel Öz koordinasyonu <b>{usd.format(option.gelOzCoordination)}</b></span></div><details><summary>Sağlayıcı planı</summary>{option.providerPlan.map(item => <p key={item.segment}><b>{item.segment}</b><br/>{item.preferredProvider} · {item.integration.replaceAll("_", " ")}</p>)}</details></article>;
}
